/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddExpenseModal: typeof import('./components/forms/AddExpenseModal.vue')['default']
    AppDropDown: typeof import('./components/ui/AppDropDown.vue')['default']
    AppFormField: typeof import('./components/ui/AppFormField.vue')['default']
    AppFormModal: typeof import('./components/ui/AppFormModal.vue')['default']
    AppModal: typeof import('./components/ui/AppModal.vue')['default']
    AppToast: typeof import('./components/ui/AppToast.vue')['default']
    BulkAddExpenseModal: typeof import('./components/forms/BulkAddExpenseModal.vue')['default']
    ExpenseOverview: typeof import('./components/expenses/ExpenseOverview.vue')['default']
    ExpenseTransactionList: typeof import('./components/expenses/ExpenseTransactionList.vue')['default']
    ExpenseTypeManagerModal: typeof import('./components/expenses/ExpenseTypeManagerModal.vue')['default']
    ExpenseView: typeof import('./components/expenses/ExpenseView.vue')['default']
    LoginFormModal: typeof import('./components/forms/LoginFormModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestFormModal: typeof import('./components/forms/TestFormModal.vue')['default']
    TransactionFormModal: typeof import('./components/forms/TransactionFormModal.vue')['default']
    UserFormModal: typeof import('./components/forms/UserFormModal.vue')['default']
  }
}
