-- Add user_id column to tests table
-- 1. Xóa bảng cũ để làm sạch dữ liệu
DROP TABLE IF EXISTS public.tests CASCADE;

-- 2. Tạo lại bảng tests với đầy đủ các cột cần thiết
CREATE TABLE public.tests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_at timestamptz,
    name text NOT NULL,
    user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL DEFAULT auth.uid()
);

-- 3. Bật Row Level Security
ALTER TABLE public.tests ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- CHÍNH SÁCH CHO CÁC BẢNG HỆ THỐNG (RBAC)
-- ==========================================

ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;

-- Quyền SELECT: Đã có ở 001, hoặc dùng lại ở đây cho chắc chắn
DROP POLICY IF EXISTS "Allow authenticated users to view roles" ON public.roles;
CREATE POLICY "Allow authenticated users to view roles" ON public.roles 
    FOR SELECT TO authenticated USING (true);

-- Quyền Xem profile cá nhân: Mỗi user tự xem được profile của chính mình để FE có thể loadUser
DROP POLICY IF EXISTS "Users can view their own profiles" ON public.profiles;
CREATE POLICY "Users can view their own profiles" ON public.profiles
    FOR SELECT TO authenticated
    USING (auth.uid() = id);

-- Quyền MANAGE (ALL): Để tránh đệ quy, ta chỉ cho phép Admin quản lý Roles 
-- bằng cách kiểm tra trực tiếp qua hàm is_admin() đã có SECURITY DEFINER
DROP POLICY IF EXISTS "Admins have full access to roles" ON public.roles;
CREATE POLICY "Admins have full access to roles" ON public.roles 
    FOR ALL TO authenticated 
    USING (public.is_admin());

-- Quyền Xem toàn bộ Profile: Admin cần xem hết để quản lý tài khoản
DROP POLICY IF EXISTS "Admins can view all profiles" ON public.profiles;
CREATE POLICY "Admins can view all profiles" ON public.profiles
    FOR SELECT TO authenticated
    USING (public.is_admin());

-- Quyền UPDATE Profile: Chỉ Admin mới được thay đổi role của người khác
DROP POLICY IF EXISTS "Admins can update user roles" ON public.profiles;
CREATE POLICY "Admins can update user roles" ON public.profiles
    FOR UPDATE TO authenticated
    USING (public.is_admin())
    WITH CHECK (public.is_admin());

-- ==========================================
-- CHÍNH SÁCH CHO TÀI NGUYÊN (TESTS)
-- ==========================================

-- 4. Chính sách SELECT: User thấy đồ của mình, Admin thấy hết
DROP POLICY IF EXISTS "Allow users to view their own tests or admins all" ON public.tests;
CREATE POLICY "Allow users to view their own tests or admins all"
    ON public.tests FOR SELECT
    TO authenticated
    USING (
        auth.uid() = user_id 
        OR EXISTS (
            SELECT 1 FROM public.profiles p
            JOIN public.roles r ON p.role_id = r.id
            WHERE p.id = auth.uid() AND r.name = 'admin'
        )
    );

-- 5. Chính sách INSERT: User chỉ được tạo cho chính mình
DROP POLICY IF EXISTS "Allow users to insert their own tests" ON public.tests;
CREATE POLICY "Allow users to insert their own tests"
    ON public.tests FOR INSERT
    TO authenticated
    WITH CHECK (auth.uid() = user_id);

-- 6. Chính sách UPDATE: User sửa đồ của mình, Admin sửa hết
DROP POLICY IF EXISTS "Allow users to update their own tests or admins all" ON public.tests;
CREATE POLICY "Allow users to update their own tests or admins all"
    ON public.tests FOR UPDATE
    TO authenticated
    USING (
        auth.uid() = user_id 
        OR EXISTS (
            SELECT 1 FROM public.profiles p
            JOIN public.roles r ON p.role_id = r.id
            WHERE p.id = auth.uid() AND r.name = 'admin'
        )
    );

-- 7. Chính sách DELETE: User xóa đồ của mình, Admin xóa hết
DROP POLICY IF EXISTS "Allow users to delete their own tests or admins all" ON public.tests;
CREATE POLICY "Allow users to delete their own tests or admins all"
    ON public.tests FOR DELETE
    TO authenticated
    USING (
        auth.uid() = user_id 
        OR EXISTS (
            SELECT 1 FROM public.profiles p
            JOIN public.roles r ON p.role_id = r.id
            WHERE p.id = auth.uid() AND r.name = 'admin'
        )
    );