-- Create expense_types table
CREATE TABLE IF NOT EXISTS public.expense_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_at timestamptz,
    name text NOT NULL,
    description text,
    user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE
);

-- Enable Row Level Security
ALTER TABLE public.expense_types ENABLE ROW LEVEL SECURITY;

-- 1. Chính sách SELECT: User thấy loại hệ thống (user_id IS NULL) HOẶC loại của chính mình
DROP POLICY IF EXISTS "View system or own expense types" ON public.expense_types;
CREATE POLICY "View system or own expense types" ON public.expense_types
    FOR SELECT TO authenticated
    USING (user_id IS NULL OR user_id = auth.uid());

-- 2. Chính sách INSERT: User chỉ được tạo loại chi phí cá nhân (user_id phải khớp với auth.uid)
DROP POLICY IF EXISTS "Insert own expense types" ON public.expense_types;
CREATE POLICY "Insert own expense types" ON public.expense_types
    FOR INSERT TO authenticated
    WITH CHECK (user_id = auth.uid());

-- 3. Chính sách UPDATE: User chỉ được sửa loại chi phí do chính họ tạo ra
DROP POLICY IF EXISTS "Update own expense types" ON public.expense_types;
CREATE POLICY "Update own expense types" ON public.expense_types
    FOR UPDATE TO authenticated
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

-- 4. Chính sách DELETE: User chỉ được xóa loại chi phí do chính họ tạo ra
DROP POLICY IF EXISTS "Delete own expense types" ON public.expense_types;
CREATE POLICY "Delete own expense types" ON public.expense_types
    FOR DELETE TO authenticated
    USING (user_id = auth.uid());

-- 5. Quyền Admin: Admin có thể quản lý tất cả (bao gồm cả loại hệ thống)
-- Giả định function is_admin() đã được định nghĩa ở migration 001
DROP POLICY IF EXISTS "Admins can manage all expense types" ON public.expense_types;
CREATE POLICY "Admins can manage all expense types" ON public.expense_types
    FOR ALL TO authenticated
    USING (public.is_admin());

-- Seed dữ liệu mẫu cho hệ thống (các loại mặc định ai cũng thấy)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM public.expense_types WHERE user_id IS NULL AND name = 'Ăn uống') THEN
        INSERT INTO public.expense_types (name, description, user_id) VALUES 
        ('Ăn uống', 'Cơm, phở, cà phê, trà sữa...', NULL),
        ('Di chuyển', 'Xăng xe, Grab, taxi, bảo dưỡng...', NULL),
        ('Nhà cửa', 'Tiền điện, nước, internet, tiền nhà...', NULL),
        ('Mua sắm', 'Quần áo, giày dép, đồ gia dụng...', NULL),
        ('Sức khỏe', 'Khám bệnh, thuốc men, thực phẩm chức năng...', NULL),
        ('Giải trí', 'Xem phim, du lịch, hội họp...', NULL),
        ('Hóa đơn', 'Điện thoại, bảo hiểm, phí dịch vụ...', NULL),
        ('Khác', 'Các khoản chi phí không tên...', NULL);
    END IF;
END $$;
