-- 1. Tạo bảng lưu trữ giao dịch thu chi
CREATE TABLE IF NOT EXISTS public.expenses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    deleted_at timestamptz,
    title text NOT NULL,
    amount bigint NOT NULL, -- Số tiền (luôn lưu số dương, dùng transaction_type để phân biệt)
    note text,
    transaction_date timestamptz DEFAULT now() NOT NULL,
    transaction_type text NOT NULL CHECK (transaction_type IN ('expense', 'income')),
    type_id bigint REFERENCES public.expense_types(id) ON DELETE SET NULL,
    user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL DEFAULT auth.uid()
);

-- 2. Bật Row Level Security
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;

-- 3. Chính sách SELECT: User thấy giao dịch của mình, Admin thấy hết
DROP POLICY IF EXISTS "Users can view own expenses or admins all" ON public.expenses;
CREATE POLICY "Users can view own expenses or admins all"
    ON public.expenses FOR SELECT
    TO authenticated
    USING (user_id = auth.uid() OR public.is_admin());

-- 4. Chính sách INSERT: User chỉ được tạo giao dịch cho chính mình
DROP POLICY IF EXISTS "Users can insert own expenses" ON public.expenses;
CREATE POLICY "Users can insert own expenses"
    ON public.expenses FOR INSERT
    TO authenticated
    WITH CHECK (user_id = auth.uid());

-- 5. Chính sách UPDATE/DELETE: User sửa/xóa đồ của mình, Admin quản lý hết
DROP POLICY IF EXISTS "Users can update own expenses or admins all" ON public.expenses;
CREATE POLICY "Users can update own expenses or admins all"
    ON public.expenses FOR UPDATE
    TO authenticated
    USING (user_id = auth.uid() OR public.is_admin());

DROP POLICY IF EXISTS "Users can delete own expenses or admins all" ON public.expenses;
CREATE POLICY "Users can delete own expenses or admins all"
    ON public.expenses FOR DELETE
    TO authenticated
    USING (user_id = auth.uid() OR public.is_admin());

-- 6. Đổ dữ liệu mẫu (Seed data) cho tài khoản admin mặc định
-- Lưu ý: Phải có user admin@example.com trước (đã tạo ở migration 003)
DO $$
DECLARE
    v_admin_id uuid;
    v_type_food bigint;
    v_type_move bigint;
    v_type_bill bigint;
    v_type_shop bigint;
    v_type_other bigint;
BEGIN
    -- Lấy ID của admin
    SELECT id INTO v_admin_id FROM public.profiles WHERE email = 'admin@example.com';

    IF v_admin_id IS NOT NULL THEN
        -- Lấy ID các loại chi phí mặc định (từ migration 005)
        SELECT id INTO v_type_food FROM public.expense_types WHERE name = 'Ăn uống' LIMIT 1;
        SELECT id INTO v_type_move FROM public.expense_types WHERE name = 'Di chuyển' LIMIT 1;
        SELECT id INTO v_type_bill FROM public.expense_types WHERE name = 'Hóa đơn' LIMIT 1;
        SELECT id INTO v_type_shop FROM public.expense_types WHERE name = 'Mua sắm' LIMIT 1;
        SELECT id INTO v_type_other FROM public.expense_types WHERE name = 'Khác' LIMIT 1;

        -- Xóa dữ liệu cũ nếu có để tránh trùng lặp khi chạy lại migration
        DELETE FROM public.expenses WHERE user_id = v_admin_id;

        -- Chèn các giao dịch mẫu
        INSERT INTO public.expenses (title, amount, transaction_type, type_id, user_id, transaction_date, note)
        VALUES 
        -- Thu nhập
        ('Lương tháng 5', 25000000, 'income', v_type_other, v_admin_id, now() - interval '5 days', 'Lương công ty chuyển'),
        ('Thưởng dự án', 5000000, 'income', v_type_other, v_admin_id, now() - interval '2 days', 'Thưởng KPI quý 1'),
        
        -- Chi tiêu
        ('Starbucks Coffee', 65000, 'expense', v_type_food, v_admin_id, now(), 'Đi cafe với bạn'),
        ('Phở Bát Đàn', 55000, 'expense', v_type_food, v_admin_id, now() - interval '1 hour', 'Ăn trưa'),
        ('Đổ xăng xe', 100000, 'expense', v_type_move, v_admin_id, now() - interval '1 day', 'Xăng xe đi làm'),
        ('Grab Ride', 45000, 'expense', v_type_move, v_admin_id, now() - interval '1 day', 'Đi tiệc'),
        ('Uniqlo Shopping', 1250000, 'expense', v_type_shop, v_admin_id, now() - interval '3 days', 'Mua áo sơ mi mới'),
        ('Tiền điện tháng 4', 850000, 'expense', v_type_bill, v_admin_id, now() - interval '4 days', 'Thanh toán qua app'),
        ('Netflix', 260000, 'expense', v_type_bill, v_admin_id, now() - interval '10 days', 'Gia hạn hàng tháng'),
        ('Mua quà sinh nhật', 500000, 'expense', v_type_other, v_admin_id, now() - interval '12 days', 'Quà cho mẹ');

    END IF;
END $$;

-- 7. Tạo function tự động cập nhật updated_at
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_expenses_updated_at
    BEFORE UPDATE ON public.expenses
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();
